// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service/service.proto

package go_micro_srv_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Header               map[string]string `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UserRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{3}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	UserType             int32    `protobuf:"varint,4,opt,name=userType,proto3" json:"userType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetUserType() int32 {
	if m != nil {
		return m.UserType
	}
	return 0
}

type CacheRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheRequest) Reset()         { *m = CacheRequest{} }
func (m *CacheRequest) String() string { return proto.CompactTextString(m) }
func (*CacheRequest) ProtoMessage()    {}
func (*CacheRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{5}
}

func (m *CacheRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheRequest.Unmarshal(m, b)
}
func (m *CacheRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheRequest.Marshal(b, m, deterministic)
}
func (m *CacheRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheRequest.Merge(m, src)
}
func (m *CacheRequest) XXX_Size() int {
	return xxx_messageInfo_CacheRequest.Size(m)
}
func (m *CacheRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CacheRequest proto.InternalMessageInfo

func (m *CacheRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CacheRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CacheResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheResponse) Reset()         { *m = CacheResponse{} }
func (m *CacheResponse) String() string { return proto.CompactTextString(m) }
func (*CacheResponse) ProtoMessage()    {}
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{6}
}

func (m *CacheResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheResponse.Unmarshal(m, b)
}
func (m *CacheResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheResponse.Marshal(b, m, deterministic)
}
func (m *CacheResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheResponse.Merge(m, src)
}
func (m *CacheResponse) XXX_Size() int {
	return xxx_messageInfo_CacheResponse.Size(m)
}
func (m *CacheResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CacheResponse proto.InternalMessageInfo

func (m *CacheResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{7}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{8}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{9}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{10}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.service.Message")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.srv.service.Message.HeaderEntry")
	proto.RegisterType((*Request)(nil), "go.micro.srv.service.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.service.Response")
	proto.RegisterType((*UserRequest)(nil), "go.micro.srv.service.UserRequest")
	proto.RegisterType((*User)(nil), "go.micro.srv.service.User")
	proto.RegisterType((*CacheRequest)(nil), "go.micro.srv.service.CacheRequest")
	proto.RegisterType((*CacheResponse)(nil), "go.micro.srv.service.CacheResponse")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.service.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.service.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.service.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.service.Pong")
}

func init() { proto.RegisterFile("proto/service/service.proto", fileDescriptor_a34e2f8c9a3669d2) }

var fileDescriptor_a34e2f8c9a3669d2 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xbb, 0xb5, 0xe3, 0xb8, 0x93, 0x22, 0x85, 0x55, 0x84, 0x22, 0x43, 0x4b, 0x58, 0x04,
	0xb8, 0x17, 0x53, 0x15, 0x09, 0x01, 0x37, 0x54, 0xa1, 0x94, 0x03, 0xa2, 0x72, 0xc9, 0x91, 0xc3,
	0x36, 0x19, 0x39, 0x56, 0x63, 0x6f, 0xd8, 0x5d, 0x47, 0xca, 0xb3, 0xf0, 0x9a, 0x3c, 0x00, 0xf2,
	0x7a, 0x6d, 0x2c, 0x64, 0x03, 0x07, 0x4e, 0xd9, 0xc9, 0xff, 0xfd, 0xbf, 0xc7, 0x33, 0x2b, 0xc3,
	0xc3, 0xad, 0x14, 0x5a, 0xbc, 0x54, 0x28, 0x77, 0xe9, 0x12, 0xeb, 0xdf, 0xc8, 0xfc, 0x4b, 0x27,
	0x89, 0x88, 0xb2, 0x74, 0x29, 0x45, 0xa4, 0xe4, 0x2e, 0xb2, 0x1a, 0xfb, 0x4e, 0x60, 0xf8, 0x09,
	0x95, 0xe2, 0x09, 0xd2, 0xf7, 0xe0, 0xad, 0x91, 0xaf, 0x50, 0x4e, 0xc9, 0xcc, 0x09, 0x47, 0x17,
	0x67, 0x51, 0x97, 0x25, 0xb2, 0x78, 0x74, 0x65, 0xd8, 0x0f, 0xb9, 0x96, 0xfb, 0xd8, 0x1a, 0x29,
	0x05, 0xf7, 0x56, 0xac, 0xf6, 0xd3, 0xc3, 0x19, 0x09, 0x8f, 0x63, 0x73, 0x0e, 0xde, 0xc2, 0xa8,
	0x85, 0xd2, 0x31, 0x38, 0x77, 0xb8, 0x9f, 0x92, 0x19, 0x09, 0x8f, 0xe2, 0xf2, 0x48, 0x27, 0x30,
	0xd8, 0xf1, 0x4d, 0x81, 0xc6, 0x75, 0x14, 0x57, 0xc5, 0xbb, 0xc3, 0x37, 0x84, 0x9d, 0xc0, 0x30,
	0xc6, 0x6f, 0x05, 0x2a, 0x5d, 0x26, 0xe7, 0x3c, 0x43, 0xeb, 0x33, 0x67, 0xf6, 0x08, 0xfc, 0x18,
	0xd5, 0x56, 0xe4, 0x0a, 0xcb, 0xd8, 0x4c, 0x25, 0x75, 0x6c, 0xa6, 0x12, 0xf6, 0x18, 0x46, 0x0b,
	0x85, 0xb2, 0x0e, 0x18, 0x83, 0x53, 0xa4, 0xab, 0x1a, 0x28, 0xd2, 0x15, 0x5b, 0x83, 0x5b, 0x02,
	0x34, 0x00, 0xbf, 0x50, 0x28, 0x5b, 0xf1, 0x4d, 0x4d, 0x1f, 0x80, 0xc7, 0x77, 0x5c, 0x73, 0x69,
	0x9b, 0xb3, 0x55, 0x9d, 0xe6, 0x34, 0x69, 0x75, 0xca, 0x97, 0xfd, 0x16, 0xa7, 0xee, 0x8c, 0x84,
	0x83, 0xb8, 0xa9, 0xd9, 0x6b, 0x38, 0xbe, 0xe4, 0xcb, 0x35, 0xb6, 0x7a, 0xf9, 0x97, 0x19, 0xb0,
	0x67, 0x70, 0xcf, 0xfa, 0xec, 0x5b, 0x36, 0x18, 0x69, 0x63, 0x21, 0x8c, 0x6f, 0xb4, 0x44, 0x9e,
	0xa5, 0x79, 0x52, 0x3f, 0x62, 0x02, 0x83, 0xa5, 0x28, 0x72, 0x6d, 0x48, 0x27, 0xae, 0x0a, 0x76,
	0x06, 0xf7, 0x5b, 0xe4, 0xaf, 0xd0, 0x0e, 0xf4, 0x14, 0xdc, 0xeb, 0x34, 0x4f, 0xca, 0x09, 0x28,
	0x2d, 0xc5, 0x1d, 0x5a, 0xd9, 0x56, 0x46, 0x17, 0xfd, 0xfa, 0xc5, 0x0f, 0x07, 0x86, 0x37, 0xd5,
	0x95, 0xa1, 0x73, 0x70, 0x2f, 0xf9, 0x66, 0x43, 0x4f, 0xba, 0x6f, 0x94, 0xed, 0x39, 0x38, 0xed,
	0x93, 0xab, 0x46, 0xd9, 0x01, 0xfd, 0x08, 0xde, 0x1c, 0xf5, 0xe7, 0x1c, 0xe9, 0x93, 0x6e, 0xb6,
	0xb5, 0xf1, 0x20, 0xe8, 0x47, 0xd8, 0x01, 0x5d, 0x80, 0x7f, 0x5d, 0x68, 0x33, 0x5e, 0xca, 0xba,
	0xc9, 0xf6, 0xce, 0x82, 0xa7, 0x7f, 0x64, 0x9a, 0x0e, 0x17, 0xe0, 0xcf, 0xf1, 0xff, 0xc7, 0x7e,
	0x05, 0xaf, 0x5a, 0x1c, 0x7d, 0xde, 0x6d, 0xf8, 0xfd, 0x02, 0x04, 0x2f, 0xfe, 0xca, 0xd5, 0xe1,
	0xe7, 0x84, 0x5e, 0x81, 0x5f, 0x2e, 0xdb, 0x2c, 0xb4, 0x67, 0x6c, 0xa5, 0xde, 0x37, 0xd2, 0xd2,
	0xc7, 0x0e, 0x42, 0x72, 0x4e, 0x6e, 0x3d, 0xf3, 0xb5, 0x79, 0xf5, 0x33, 0x00, 0x00, 0xff, 0xff,
	0x24, 0xad, 0x34, 0xb7, 0x8c, 0x04, 0x00, 0x00,
}
