# 启动模式
debug: true

# 项目配置
service:
  name: go.micro.web.adminApi
  port: :9081
  version: latest

#jwt key
jwt:
  signKey: api
  timeOut: 10

# mysql配置
mysql:
  username : root
  port : 3306
  password : gogocuri
  db_name : rbac
  address : 192.168.0.162

# redis 配置
redis:
  host: 192.168.0.162
  port: 6379
  auth: DareJoejoe
  db:  12


# consul 配置
consul: 127.0.0.1:8300

# jaeger 配置
jaeger:  127.0.0.1:6831

# nsq 配置
nsq:
  address: 192.168.0.180:4150
  lookup: 192.168.0.180:4161
  maxInFlight: 1