// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-07-30 19:37:37.125053 +0800 CST m=+0.037003424

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "微服务的管理端api文档demo",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "host": "localhost:9081",
    "basePath": "/api/admin",
    "paths": {
        "/user/edit_pwd": {
            "post": {
                "security": [
                    {
                        "MustToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户修改密码",
                "parameters": [
                    {
                        "description": "修改密码",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.editPwdReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{code:0,msg:ok}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "{code:1,msg:无效的请求参数}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "500": {
                        "description": "{code:-1,msg:服务器故障}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "security": [
                    {
                        "MustToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户信息及可访问的权限菜单",
                "responses": {
                    "200": {
                        "description": "{code:0,msg:ok}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "{code:1,msg:无效的请求参数}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "500": {
                        "description": "{code:-1,msg:服务器故障}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{code:0,msg:ok,data:{token:}}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "{code:1,msg:无效的请求参数}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "500": {
                        "description": "{code:-1,msg:服务器故障}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "get": {
                "security": [
                    {
                        "MustToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "{code:0,msg:ok}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "{code:1,msg:无效的请求参数}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "500": {
                        "description": "{code:-1,msg:服务器故障}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    }
                }
            }
        },
        "/user_mana/list": {
            "get": {
                "security": [
                    {
                        "MustToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_mana   用户管理模块"
                ],
                "summary": "获取admin用户列表",
                "responses": {
                    "200": {
                        "description": "用户列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AdminUser"
                            }
                        }
                    },
                    "400": {
                        "description": "{code:1,msg:无效的请求参数}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "500": {
                        "description": "{code:-1,msg:服务器故障}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ResponseModel": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "handler.editPwdReq": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "description": "新密码",
                    "type": "string"
                },
                "old_password": {
                    "description": "旧密码",
                    "type": "string"
                }
            }
        },
        "handler.login": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "model.AdminUser": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "real_name": {
                    "description": "真实姓名",
                    "type": "string"
                },
                "salt": {
                    "type": "string"
                },
                "status": {
                    "description": "状态(1:启用  2.禁用)",
                    "type": "integer"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "MustToken": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
