// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-07-30 11:09:50.712342 +0800 CST m=+0.030111052

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "微服务的管理端api文档demo",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "host": "localhost:9081",
    "basePath": "/api/admin",
    "paths": {
        "/api/admin/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "json",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{code:0,msg:ok,data:{token:}}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "{code:1,msg:无效的请求参数}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    },
                    "500": {
                        "description": "{code:-1,msg:服务器故障}",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ResponseModel": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "handler.login": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
